import { PhoneAndroid } from '@mui/icons-material'
import Head from 'next/head'
import Image from 'next/image'
import { Parallax } from 'react-scroll-parallax'
import Card from '../components/Card/Card'
import styles from '../styles/About.module.css'

export default function Contact() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Contact</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <div className={styles.cover}>

                    <div className={styles.background}>

                        <div className={styles.circle}></div>
                    </div>
                    <h3 className={styles.title}>
                        Contact - Us
                    </h3>

                    <p className={styles.description}>
                        <PhoneAndroid /> +977-9864567389
                    </p>
                    <p className={styles.description}>
                        example@gmail.com
                    </p>

                </div>
                <div className={styles.grid}>
                        <h1 className='contact-header'>Get in Touch.</h1>
                    <style jsx>
                        {`
                        .contact-header{
                            padding: .6em 0;
                        }
                    .map{
                        width:1000px;
                        // background: red;
                        height: 500px;
                        box-shadow: 1px 2px 3px rgba(0,0,0,0.3);
                        padding: 40px;
                    }
                `}
                    </style>
                    <div className={styles.flex_wrap}>

                        <Card
                            title='Who are we'
                            description="Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book."
                        />
                        <Card
                            title='Who are we?'
                            description="Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book."
                        />
                        <Card
                            title='why we do it?'
                            description="Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book."
                        />
                    </div>

                </div>
            </main>

        </div>
    )
}
