import Head from 'next/head'
import Image from 'next/image'
import Container from '../components/container/Container'
import styles from '../styles/Home.module.css'
export default function Tutorial() {
  return (
    <Container>
      <Head>
        <title>blogs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
        Learn to Code
        </h1>

        

        <div className={styles.grid}>
          <div className={styles.card}>
            <h2>HTML5 &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </div>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>CSS3 &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <div
            className={styles.card}
          >
            <h2>Javascript &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </div>

          <div
            className={styles.card}
          >
            <h2>Bootstrap &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </div>
        </div>
      </main>

      
    </Container>
  )
}
