      
import Head from 'next/head'
import { useRouter } from 'next/router'
import { useEffect, useState } from 'react'
import Container from '../../components/container/Container'
import styles from '../../styles/Home.module.css'
// export function getStaticPaths(ctx: any) {
//     const paths = ctx;
//     return{
//         props:{
//             paths,
//             fallback: false
//         }
//     }
// }
// export function getStaticProps(ctx: any){
//     return{
//         props: ctx
//     }
// }
export default function Slug() {
    const router = useRouter();
    const [blogdata,setBlogData] = useState<any>([]);
    useEffect(() => {
      fetch(`/api/blogBySlug?slug=${router.query.slug}`)
      .then((res) => {
         return res.json()
      }).then((data) =>{
        console.log(data)
          setBlogData(JSON.parse(data))
      })
    },[router.query.slug])
  return (
    <Container>
      <Head>
        <title>{router.query.slug}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          {blogdata.title} - course       </h1>

      

        <div className={styles.grid}>
                <h2>{blogdata.title}</h2>
                <p>{blogdata.description}</p>
        </div>
      </main>

      
    </Container>
  )
}
