      
import Head from 'next/head'
import Image from 'next/image'
import { useRouter } from 'next/router'
import { useEffect } from 'react'
import Container from '../../components/container/Container'
import styles from '../../styles/Home.module.css'
// export function getStaticPaths(ctx: any) {
//     const paths = ctx;
//     return{
//         props:{
//             paths,
//             fallback: false
//         }
//     }
// }
// export function getStaticProps(ctx: any){
//     return{
//         props: ctx
//     }
// }
export default function Slug({ctx}: any) {
    const router = useRouter();
    useEffect(() => {
        console.log(ctx)
    },[ctx])
  return (
    <Container>
      <Head>
        <title>{router.query.slug}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to {router.query.slug}
        </h1>

      

        <div className={styles.grid}>

        </div>
      </main>

      
    </Container>
  )
}
