import Head from 'next/head'
import React from 'react';
import Container from '../container/Container'
import styles from '../../styles/PageLayout.module.css'

interface PropsTypes {
  pageTitle: string,
  children: React.ReactNode,
  description: string,
  pageHeading: string,
  showCover: boolean
}
function PageLayout({ pageTitle, description, children, pageHeading, showCover }: PropsTypes) {
  return (
    <Container>
      <Head>
        <title> {pageTitle}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {showCover &&
          <div className={styles.cover}>
            <div className={styles.background}>
              <div className={styles.circle}></div>
            </div>
            {/* <div className={styles.d_flex} > */}
              <h1 className={styles.title}>
                {pageHeading}
              </h1>
              <p className={styles.description}>
                {description}
              </p>
            {/* </div> */}
          </div>
        }
        <div className={styles.grid}>
          {children}

        </div>
      </main>
    </Container>
  )
}



export default PageLayout;
